name: Publish Tar
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'latest'
  push:
    branches:
      - main

jobs:
  publish-tar:
    permissions: write-all
    name: Publish tar as release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive
        run: tar -cf archive.tar ./*

      - name: Output version from file to variable
        id: version
        run: echo "::set-output name=version::$(cat version)"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: archive.tar
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || steps.version.outputs.version }}
          name:  Release for Zen - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || steps.version.outputs.version }}
          body: |
            ### Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || steps.version.outputs.version }}
            - sha: ${{ github.sha }}
